### PR TITLE
fix query param deprecation and bump streamlit to 1.30

### LINKED ISSUE #39: Fix usage of deprecated experimental_get_query_params
With streamlit 1.30.0 `st.experimental_get_query_params` now throws a deprecation warning.

https://docs.streamlit.io/library/api-reference/utilities/st.experimental_get_query_params

### PR DESCRIPTION
**Pull request by 444B**
Changes:
1) Update main.py
changed st.experimental_get_query_params to st.query_params
- reason (st.experimental_get_query_params deprecation)
https://docs.streamlit.io/library/api-reference/utilities/st.experimental_get_query_params

2) Update Pipfile.lock
bumping streamlit version from 1.13 to 1.30
- requires testing for breaking changes

This should resolve https://github.com/jrieke/streamlit-analytics/issues/39

### CODE REVIEW

**Comment by 444B** [comment]
@mt-krainski visibility

**Comment by 444B** [comment]
@jrieke Are you available to take a look at this?
Please let us know if you are still actively maintaining this repo

**Comment by RazHadas** [comment]
Hi,
still not working for me. can you please more detail how to do it.
I use streamlit 1.30

**Comment by 444B** [comment]
@RazHadas
I am hoping to get the change made in streamlit-analytics with this pull request

In the meantime, you can maybe specify in your requirements.txt or pipfile or whichever dependency file you have to use a streamlit version that is prior to 1.30

**Comment by RazHadas** [comment]
Thanks for the quick response. I will check it.

**Comment by 444B** [comment]
I messaged the author on Linkedin but no response so it would seem this project is not maintained... 
Perhaps we will need to fork this repo and fix this issues independently but then the issue becomes around publishing the packages via pypi and pip, which I have less experience with but certainly can learn
Ill create an new issue stating this if we take this path
Tag me if you are interested in contributing
#TODO look into the licence of this repo and understand the implications of forking 

@jrieke visibility

**Comment by RazHadas** [comment]
The analytics is streamlit is really problematic. I already try for few days to get unique page views.

**Comment by 444B** [comment]
> The analytics is streamlit is really problematic. I already try for few days to get unique page views.

Hi @RazHadas 
I have reached out to @jrieke on linkedin, here on Github and also just sent them an email to ask about how we can contribute and if the repo is being maintained or not
Without a response from them soon, I will be forking the project and fixing these issue in a new repo
Ill update you if that occurs and place it into this repo as a new issue

**Comment by RazHadas** [comment]
Sounds good. I just find script that get ip and screen resolution from user in streamlit, I want to improve the analytics.
By the way, did you manage to work with Google analytics 4 in streamlit?

**Comment by 444B** [comment]
Note: I am pushing this to my own fork but it seems be to included in this PR
Not sure why that would be tbh

@RazHadas The GA4 integration is something I want to work on in the future

**Pull request closed without merging**
